language: swift

os: [osx, linux]
osx_image: xcode10.1
dist: xenial

matrix:
  allow_failures:
    - os: linux
  fast_finish: true

branches:
  only: [master]

cache:
  directories: [/usr/local/lib/mint, Vendor/Mint/.build]

script: make bootstrap test

after_script:
  - make ensure_clean

notifications:
  email: false
