language: swift

os: [osx, linux]
osx_image: xcode10.1
dist: xenial

env:
  - SPECTEST_PATH=/tmp/wast_wasm

matrix:
  allow_failures:
    - os: linux
  fast_finish: true

branches:
  only: [master]

cache:
  directories: [/usr/local/lib/mint, Vendor/Mint/.build]

before_script: |
  git clone --depth 1 https://github.com/akkyie/wast-wasm $SPECTEST_PATH

script:
  - make bootstrap test
  - make format
  - make ensure_clean

after_success:
  - make spectest

notifications:
  email: false
